<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index');
Route::get('home','IndexController@index');
Route::get('pricing','IndexController@pricing');
Route::get('faq','IndexController@faq');
Route::get('account','IndexController@account');
Route::get('contact','IndexController@contact');
// Route::get('Plugin', function () {
// 	return view('apps.frontEnd.pages.index');
// });
Route::get('plugin','SitePluginController@SiteIndex');

// Admin Panel
//category
Route::get('category','CategoryController@index');
Route::post('category/save','CategoryController@store');
Route::get('category/edit/{id}','CategoryController@show');
Route::get('category/delete/{id}','CategoryController@destroy');
Route::post('category/update/{id}','CategoryController@update');
//components
Route::get('components','ComponentController@index');
Route::post('components/save','ComponentController@store');
Route::get('components/edit/{id}','ComponentController@show');
Route::get('components/delete/{id}','ComponentController@destroy');
Route::post('components/update/{id}','ComponentController@update');
//FabricType
Route::get('FabricType','FabricTypeController@index');
Route::post('FabricType/save','FabricTypeController@store');
Route::get('FabricType/edit/{id}','FabricTypeController@show');
Route::get('FabricType/delete/{id}','FabricTypeController@destroy');
Route::post('FabricType/update/{id}','FabricTypeController@update');
//DressFitting
Route::get('DressFitting','DressFittingController@index');
Route::post('DressFitting/save','DressFittingController@store');
Route::get('DressFitting/edit/{id}','DressFittingController@show');
Route::get('DressFitting/delete/{id}','DressFittingController@destroy');
Route::post('DressFitting/update/{id}','DressFittingController@update');
//FrontDesign
Route::get('FrontDesign','FrontDesignController@index');
Route::post('FrontDesign/save','FrontDesignController@store');
Route::get('FrontDesign/edit/{id}','FrontDesignController@show');
Route::get('FrontDesign/delete/{id}','FrontDesignController@destroy');
Route::post('FrontDesign/update/{id}','FrontDesignController@update');
//BackDesign
Route::get('BackDesign','BackDesignController@index');
Route::post('BackDesign/save','BackDesignController@store');
Route::get('BackDesign/edit/{id}','BackDesignController@show');
Route::get('BackDesign/delete/{id}','BackDesignController@destroy');
Route::post('BackDesign/update/{id}','BackDesignController@update');
//FrontDepthDesign
Route::get('FrontDepthDesign','FrontDepthDesignController@index');
Route::post('FrontDepthDesign/save','FrontDepthDesignController@store');
Route::get('FrontDepthDesign/edit/{id}','FrontDepthDesignController@show');
Route::get('FrontDepthDesign/delete/{id}','FrontDepthDesignController@destroy');
Route::post('FrontDepthDesign/update/{id}','FrontDepthDesignController@update');
//BackDepthDesign
Route::get('BackDepthDesign','BackDepthDesignController@index');
Route::post('BackDepthDesign/save','BackDepthDesignController@store');
Route::get('BackDepthDesign/edit/{id}','BackDepthDesignController@show');
Route::get('BackDepthDesign/delete/{id}','BackDepthDesignController@destroy');
Route::post('BackDepthDesign/update/{id}','BackDepthDesignController@update');
//SleeveDesign
Route::get('SleeveDesign','SleeveDesignController@index');
Route::post('SleeveDesign/save','SleeveDesignController@store');
Route::get('SleeveDesign/edit/{id}','SleeveDesignController@show');
Route::get('SleeveDesign/delete/{id}','SleeveDesignController@destroy');
Route::post('SleeveDesign/update/{id}','SleeveDesignController@update');
//AddonsClosing
Route::get('AddonsClosing','AddonsClosingController@index');
Route::post('AddonsClosing/save','AddonsClosingController@store');
Route::get('AddonsClosing/edit/{id}','AddonsClosingController@show');
Route::get('AddonsClosing/delete/{id}','AddonsClosingController@destroy');
Route::post('AddonsClosing/update/{id}','AddonsClosingController@update');
//AddonsDelivery
Route::get('AddonsDelivery','AddonsDeliveryCategoryController@index');
Route::post('AddonsDelivery/save','AddonsDeliveryCategoryController@store');
Route::get('AddonsDelivery/edit/{id}','AddonsDeliveryCategoryController@show');
Route::get('AddonsDelivery/delete/{id}','AddonsDeliveryCategoryController@destroy');
Route::post('AddonsDelivery/update/{id}','AddonsDeliveryCategoryController@update');
//AddonsOther
Route::get('AddonsOther','AddonsOtherController@index');
Route::post('AddonsOther/save','AddonsOtherController@store');
Route::get('AddonsOther/edit/{id}','AddonsOtherController@show');
Route::get('AddonsOther/delete/{id}','AddonsOtherController@destroy');
Route::post('AddonsOther/update/{id}','AddonsOtherController@update');
//AddonsTopLinning
Route::get('AddonsTopLinning','AddonsTopLinningController@index');
Route::post('AddonsTopLinning/save','AddonsTopLinningController@store');
Route::get('AddonsTopLinning/edit/{id}','AddonsTopLinningController@show');
Route::get('AddonsTopLinning/delete/{id}','AddonsTopLinningController@destroy');
Route::post('AddonsTopLinning/update/{id}','AddonsTopLinningController@update');
//Measurement
Route::get('Measurement','MeasurementController@index');
Route::post('Measurement/save','MeasurementController@store');
Route::get('Measurement/edit/{id}','MeasurementController@show');
Route::get('Measurement/delete/{id}','MeasurementController@destroy');
Route::post('Measurement/update/{id}','MeasurementController@update');
//SystemMeasurement
Route::get('SystemMeasurement','SystemMeasurementController@index');
Route::post('SystemMeasurement/save','SystemMeasurementController@store');
Route::get('SystemMeasurement/edit/{id}','SystemMeasurementController@show');
Route::get('SystemMeasurement/delete/{id}','SystemMeasurementController@destroy');
Route::post('SystemMeasurement/update/{id}','SystemMeasurementController@update');

// Route::get('/home', 'HomeController@index')->name('home');


//SiteSetting
Route::get('SiteSetting','SiteSettingController@index');
Route::post('SiteSetting/save','SiteSettingController@store');
Route::get('SiteSetting/edit/{id}','SiteSettingController@show');
Route::get('SiteSetting/delete/{id}','SiteSettingController@destroy');
Route::post('SiteSetting/update/{id}','SiteSettingController@update');
//Slider
Route::get('Slider','SliderController@index');
Route::post('Slider/save','SliderController@store');
Route::get('Slider/edit/{id}','SliderController@show');
Route::get('Slider/delete/{id}','SliderController@destroy');
Route::post('Slider/update/{id}','SliderController@update');
//AboutUs
Route::get('AboutUs','AboutUsController@index');
Route::post('AboutUs/save','AboutUsController@store');
Route::get('AboutUs/edit/{id}','AboutUsController@show');
Route::get('AboutUs/delete/{id}','AboutUsController@destroy');
Route::post('AboutUs/update/{id}','AboutUsController@update');
//FreePickup
Route::get('FreePickup','FreePickupController@index');
Route::post('FreePickup/save','FreePickupController@store');
Route::get('FreePickup/edit/{id}','FreePickupController@show');
Route::get('FreePickup/delete/{id}','FreePickupController@destroy');
Route::post('FreePickup/update/{id}','FreePickupController@update');
//OnlineStore
Route::get('OnlineStore','OnlineStoreController@index');
Route::post('OnlineStore/save','OnlineStoreController@store');
Route::get('OnlineStore/edit/{id}','OnlineStoreController@show');
Route::get('OnlineStore/delete/{id}','OnlineStoreController@destroy');
Route::post('OnlineStore/update/{id}','OnlineStoreController@update');
//WhyUs
Route::get('WhyUs','WhyUsController@index');
Route::post('WhyUs/save','WhyUsController@store');
Route::get('WhyUs/edit/{id}','WhyUsController@show');
Route::get('WhyUs/delete/{id}','WhyUsController@destroy');
Route::post('WhyUs/update/{id}','WhyUsController@update');
//Pricing
Route::get('Pricing','PricingController@index');
Route::post('Pricing/save','PricingController@store');
Route::get('Pricing/edit/{id}','PricingController@show');
Route::get('Pricing/delete/{id}','PricingController@destroy');
Route::post('Pricing/update/{id}','PricingController@update');
//Faq
Route::get('Faq','FaqController@index');
Route::post('Faq/save','FaqController@store');
Route::get('Faq/edit/{id}','FaqController@show');
Route::get('Faq/delete/{id}','FaqController@destroy');
Route::post('Faq/update/{id}','FaqController@update');